Repository trinityng/Biller, pull requests merged in 2020-04, with the labels that each got.

#24 Changed setup page for integration with plaid
  client/package.json
  client/src/components/setup/ModalForm.jsx
  client/src/components/setup/PlaidInstance.jsx
  client/src/components/setup/SetupForm.css
  client/src/components/setup/SetupForm.jsx
  client/src/components/setup/SetupFormInstance.jsx
  client/src/pages/SetupPage.js
Labels: fe, sprint-2

#45 Due Date Feature
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/api/plaid.api.js
  client/src/components/RangeDatePicker.jsx
  client/src/components/Register.jsx
  client/src/components/blog/UsersByDevice.js
  client/src/components/common/BillDueDate.js
  client/src/constants.js
  client/src/store/actions/plaid.action.js
  client/src/store/reducers/plaidReducer.js
  client/src/views/BillOverView/BillOverview.js
  server/Plaid_API/__pycache__/urls.cpython-37.pyc
  server/Plaid_API/__pycache__/views.cpython-37.pyc
  server/Plaid_API/views.py
Labels: fe, sprint-3, sprint-4

#47 Email notification and threading
  .gitignore
  client/src/constants.js
  server/.DS_Store
  server/.gitignore
  server/Authentication/migrations/0001_initial.py
  server/Authentication/validators.py
  server/Authentication/views.py
  server/Plaid_API/__pycache__/__init__.cpython-37.pyc
  server/Plaid_API/__pycache__/models.cpython-37.pyc
  server/Plaid_API/__pycache__/urls.cpython-37.pyc
  server/Plaid_API/__pycache__/views.cpython-37.pyc
  server/Plaid_API/migrations/__pycache__/0001_initial.cpython-37.pyc
  server/Plaid_API/urls.py
  server/Plaid_API/views.py
  server/server/settings.py
Labels: be

#48 Add notification and reorganized code
  client/package.json
  server/Authentication/admin.py
  server/Plaid_API/__init__.py
  server/Plaid_API/__pycache__/__init__.cpython-37.pyc
  server/Plaid_API/__pycache__/models.cpython-37.pyc
  server/Plaid_API/__pycache__/urls.cpython-37.pyc
  server/Plaid_API/__pycache__/views.cpython-37.pyc
  server/Plaid_API/email.py
  server/Plaid_API/helpers.py
  server/Plaid_API/migrations/__pycache__/0001_initial.cpython-37.pyc
  server/Plaid_API/models.py
  server/Plaid_API/threads.py
  server/Plaid_API/views.py
  server/server/settings.py
Labels: be

#50 Dashboard ui improvement + clean up code
  client/src/App.js
  client/src/api/plaid.api.js
  client/src/components/Home.js
  client/src/components/Link.js
  client/src/components/Transaction.jsx
  client/src/components/blog/AccountBalances.js
  client/src/components/blog/UsersByDevice.js
  client/src/components/dashboard/AccountBalances.js
  client/src/components/dashboard/BillDueDate.js
  client/src/components/dashboard/MonthlyBills.js
  client/src/components/dashboard/TopCategories.js
  client/src/components/dashboard/Transaction.jsx
  client/src/components/landing/Banner.jsx
  client/src/components/layout/MainNavbar/Navbar/NavbarNav.js
  client/src/components/layout/MainNavbar/Navbar/Notifications.js
  client/src/components/layout/MainNavbar/Navbar/UserActions.js
  client/src/components/layout/MainSidebar/SidebarMainNavbar.js
  client/src/components/setup/SetupAccounts.js
  client/src/data/sidebar-nav-items.js
  client/src/pages/HomePage.js
  client/src/pages/LoginPage.js
  client/src/router/DashboardRoutes.js
  client/src/router/RoutesComponent.js
  client/src/shards-dashboard/add-new-post.html
  client/src/shards-dashboard/assets/btn-documentation.png
  client/src/shards-dashboard/assets/btn-learn-more.png
  client/src/shards-dashboard/assets/btn-live-preview.png
  client/src/shards-dashboard/assets/demo-preview.gif
  client/src/shards-dashboard/assets/preview.png
  client/src/shards-dashboard/components-blog-posts.html
  client/src/shards-dashboard/errors.html
  client/src/shards-dashboard/form-components.html
  client/src/store/actions/plaid.action.js
  client/src/store/reducers/plaidReducer.js
  client/src/views/BillOverView/BillOverview.js
  client/src/views/BillOverView/defaultProps.json
  client/src/views/Transactions.js
  client/src/views/UserProfile.js
  server/Plaid_API/__pycache__/__init__.cpython-37.pyc
  server/Plaid_API/__pycache__/models.cpython-37.pyc
  server/Plaid_API/__pycache__/urls.cpython-37.pyc
  server/Plaid_API/__pycache__/views.cpython-37.pyc
  server/Plaid_API/migrations/__pycache__/0001_initial.cpython-37.pyc
  server/Plaid_API/views.py
  server/server/settings.py
Labels: be, enhancement, fe, sprint-4

#53 Ui improvements
  client/src/App.js
  client/src/api/login.api.js
  client/src/assets/flags/flag-au.png
  client/src/assets/flags/flag-jp.png
  client/src/assets/flags/flag-uk.png
  client/src/assets/flags/flag-us.png
  client/src/assets/user-profile/boy.png
  client/src/assets/user-profile/female.png
  client/src/assets/user-profile/girl.png
  client/src/assets/user-profile/male.png
  client/src/assets/user-profile/man.png
  client/src/assets/user-profile/old_female.png
  client/src/assets/user-profile/old_male.png
  client/src/components/dashboard/Transaction.jsx
  client/src/components/layout/MainNavbar/MainNavbar.js
  client/src/components/layout/MainNavbar/Navbar/UserActions.js
  client/src/components/layout/MainSidebar/SidebarNavItem.js
  client/src/components/layout/MainSidebar/SidebarNavItems.js
  client/src/components/user-profile/UserAccountDetails.js
  client/src/components/user-profile/UserDetails.js
  client/src/constants.js
  client/src/data/sidebar-nav-items.js
  client/src/images/avatars/0.jpg
  client/src/images/avatars/1.jpg
  client/src/images/avatars/2.jpg
  client/src/images/avatars/3.jpg
  client/src/images/sales-overview/no-product-image.jpg
  client/src/images/sales-overview/product-basics.jpg
  client/src/images/sales-overview/product-order-1.jpg
  client/src/images/sales-overview/product-order-2.jpg
  client/src/images/sales-overview/product-order-3.jpg
  client/src/images/sales-overview/product-shoes.jpg
  client/src/images/sales-overview/product-sportswear.jpg
  client/src/images/sales-overview/product-sweaters.jpg
  client/src/images/shards-dashboards-logo-danger.svg
  client/src/images/shards-dashboards-logo-info.svg
  client/src/images/shards-dashboards-logo-java.svg
  client/src/images/shards-dashboards-logo-royal-blue.svg
  client/src/images/shards-dashboards-logo-salmon.svg
  client/src/images/shards-dashboards-logo-secondary.svg
  client/src/images/shards-dashboards-logo-success.svg
  client/src/images/shards-dashboards-logo-warning.svg
  client/src/images/shards-dashboards-logo.svg
  client/src/router/DashboardRoutes.js
  client/src/views/BillOverView/BillOverview.js
  client/src/views/Transactions.js
  client/src/views/UserProfile.js
  server/Plaid_API/__pycache__/views.cpython-37.pyc
  server/Plaid_API/views.py
Labels: enhancement, fe, sprint-4

#55 Capitalize name
  server/Plaid_API/views.py
Labels: be

#56 [Bugfix] Fix Login-Logout issue
  client/src/App.js
  client/src/store/reducers/plaidReducer.js
  server/Plaid_API/__pycache__/views.cpython-37.pyc
Labels: bug, fe, sprint-4

#59 Round smallstat numbers
  client/src/views/BillOverView/BillOverview.js
Labels: enhancement, fe, sprint-4

#60 Added more unit testing
  server/Plaid_API/__pycache__/__init__.cpython-37.pyc
  server/Plaid_API/__pycache__/models.cpython-37.pyc
  server/Plaid_API/__pycache__/urls.cpython-37.pyc
  server/Plaid_API/migrations/__pycache__/0001_initial.cpython-37.pyc
  server/Plaid_API/tests.py
  server/Plaid_API/threads.py
  server/Plaid_API/views.py
Labels: be, enhancement, sprint-4
